import type { MapBubble } from "@/lib/mapClustering";
import { isOnCampus } from "@/lib/campus";

/**
 * Mock events pinned to real University of Waterloo locations.
 * Coordinates verified against UW campus map.
 */
const RAW_MOCK_EVENTS: Omit<MapBubble, "onCampus">[] = [
  // ── PAC ────────────────────────────────────────────────────────────────
  {
    id: "mock-1",
    title: "3v3 Basketball",
    emoji: "🏀",
    category: "Sports",
    zone: "PAC Courts",
    joined: 3,
    maxPeople: 6,
    startingIn: "Today 4:00 PM",
    duration: "1 hr",
    distance: "-",
    description: "Pickup 3v3 at the PAC outdoor courts. All skill levels.",
    lat: 43.4736,
    lng: -80.5470,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 2 * 60 * 60_000,
  },
  {
    id: "mock-2",
    title: "Morning Swim Lanes",
    emoji: "🏊",
    category: "Sports",
    zone: "PAC Pool",
    joined: 2,
    maxPeople: 5,
    startingIn: "Tomorrow 7:00 AM",
    duration: "1 hr",
    distance: "-",
    description: "Early morning lap swim. Bringing your own gear.",
    lat: 43.4740,
    lng: -80.5465,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 19 * 60 * 60_000,
  },
  {
    id: "mock-3",
    title: "Gym Lift Session",
    emoji: "💪",
    category: "Sports",
    zone: "PAC Gym",
    joined: 1,
    maxPeople: 4,
    startingIn: "Tomorrow 8:00 AM",
    duration: "1 hr",
    distance: "-",
    description: "Morning lift - chest & back day.",
    lat: 43.4738,
    lng: -80.5468,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 20 * 60 * 60_000,
  },

  // ── SLC ────────────────────────────────────────────────────────────────
  {
    id: "mock-4",
    title: "Smash Bros Casual",
    emoji: "🎮",
    category: "Gaming",
    zone: "SLC Game Room",
    joined: 5,
    maxPeople: 8,
    startingIn: "Today 8:00 PM",
    duration: "2 hrs",
    distance: "-",
    description: "Casual Smash Ultimate - all characters welcome.",
    lat: 43.4718,
    lng: -80.5442,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 6 * 60 * 60_000,
  },
  {
    id: "mock-5",
    title: "Acoustic Jam",
    emoji: "🎸",
    category: "Music",
    zone: "SLC Atrium",
    joined: 3,
    maxPeople: 6,
    startingIn: "Today 5:00 PM",
    duration: "2 hrs",
    distance: "-",
    description: "Bring your instrument or just vibe. Acoustic only.",
    lat: 43.4720,
    lng: -80.5438,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 3 * 60 * 60_000,
  },
  {
    id: "mock-6",
    title: "Bomber Pub Night",
    emoji: "🍺",
    category: "Social",
    zone: "Bomber Bar (SLC)",
    joined: 8,
    maxPeople: 15,
    startingIn: "Tonight 9:00 PM",
    duration: "2 hrs",
    distance: "-",
    description: "End-of-week Bomber night. Open to everyone 19+.",
    lat: 43.4716,
    lng: -80.5446,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 7 * 60 * 60_000,
  },
  {
    id: "mock-7",
    title: "Board Game Night",
    emoji: "🎲",
    category: "Gaming",
    zone: "SLC Turnkey Desk",
    joined: 4,
    maxPeople: 8,
    startingIn: "Today 7:00 PM",
    duration: "3 hrs",
    distance: "-",
    description: "Borrowing games from Turnkey. Catan, Ticket to Ride, etc.",
    lat: 43.4717,
    lng: -80.5444,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 5 * 60 * 60_000,
  },

  // ── DC / Dana Porter ────────────────────────────────────────────────────
  {
    id: "mock-8",
    title: "CS 136 Study Group",
    emoji: "📚",
    category: "Study",
    zone: "DC Library 2nd Floor",
    joined: 2,
    maxPeople: 5,
    startingIn: "Today 6:00 PM",
    duration: "2 hrs",
    distance: "-",
    description: "Midterm prep - pointers, linked lists, recursion.",
    lat: 43.4725,
    lng: -80.5430,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 4 * 60 * 60_000,
  },
  {
    id: "mock-9",
    title: "Dana Porter Silent Study",
    emoji: "🤫",
    category: "Study",
    zone: "Dana Porter Library",
    joined: 3,
    maxPeople: 6,
    startingIn: "Today 2:00 PM",
    duration: "4 hrs",
    distance: "-",
    description: "Silent study bloc. Headphones, no talking.",
    lat: 43.4709,
    lng: -80.5430,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 0.5 * 60 * 60_000,
  },

  // ── MC ─────────────────────────────────────────────────────────────────
  {
    id: "mock-10",
    title: "MATH 135 Cram",
    emoji: "✏️",
    category: "Study",
    zone: "MC Study Hall",
    joined: 5,
    maxPeople: 6,
    startingIn: "Tonight 9:00 PM",
    duration: "3 hrs",
    distance: "-",
    description: "Final exam cram - proofs and number theory.",
    lat: 43.4724,
    lng: -80.5421,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 7 * 60 * 60_000,
  },

  // ── EV3 / Engineering ──────────────────────────────────────────────────
  {
    id: "mock-11",
    title: "Hackathon Kickoff",
    emoji: "💻",
    category: "Study",
    zone: "EV3 Atrium",
    joined: 6,
    maxPeople: 12,
    startingIn: "Today 6:00 PM",
    duration: "12 hrs",
    distance: "-",
    description: "24h hack starting here. Team up or come solo.",
    lat: 43.4729,
    lng: -80.5418,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 4 * 60 * 60_000,
  },

  // ── Peter Russell Rock Garden ──────────────────────────────────────────
  {
    id: "mock-12",
    title: "Rock Garden Music Set",
    emoji: "🎵",
    category: "Music",
    zone: "Peter Russell Rock Garden",
    joined: 10,
    maxPeople: 30,
    startingIn: "Today 3:30 PM",
    duration: "1.5 hrs",
    distance: "-",
    description: "Outdoor acoustic + electric sets at the rock garden amphitheatre.",
    lat: 43.4672,
    lng: -80.5415,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 1.5 * 60 * 60_000,
  },
  {
    id: "mock-13",
    title: "Sunset Chill Session",
    emoji: "🌅",
    category: "Social",
    zone: "Peter Russell Rock Garden",
    joined: 5,
    maxPeople: 12,
    startingIn: "Today 7:30 PM",
    duration: "1 hr",
    distance: "-",
    description: "Just hanging at the rock garden as the sun goes down. Bring snacks.",
    lat: 43.4673,
    lng: -80.5413,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 5.5 * 60 * 60_000,
  },

  // ── Columbia Fields / Lake ─────────────────────────────────────────────
  {
    id: "mock-14",
    title: "Soccer Pickup",
    emoji: "⚽",
    category: "Sports",
    zone: "Columbia Fields",
    joined: 7,
    maxPeople: 14,
    startingIn: "Tomorrow 3:00 PM",
    duration: "1.5 hrs",
    distance: "-",
    description: "Casual pickup - bring cleats or running shoes.",
    lat: 43.4755,
    lng: -80.5480,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 26 * 60 * 60_000,
  },
  {
    id: "mock-15",
    title: "Columbia Lake Walk",
    emoji: "🦆",
    category: "Social",
    zone: "Columbia Lake",
    joined: 3,
    maxPeople: 8,
    startingIn: "Tomorrow 10:00 AM",
    duration: "1 hr",
    distance: "-",
    description: "Lap around the lake. Easy pace, good vibes.",
    lat: 43.4700,
    lng: -80.5558,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 22 * 60 * 60_000,
  },

  // ── REV ────────────────────────────────────────────────────────────────
  {
    id: "mock-16",
    title: "REV Quad Frisbee",
    emoji: "🥏",
    category: "Sports",
    zone: "REV Quad",
    joined: 4,
    maxPeople: 10,
    startingIn: "Today 5:30 PM",
    duration: "1 hr",
    distance: "-",
    description: "Ultimate frisbee warmup - beginners very welcome.",
    lat: 43.4699,
    lng: -80.5537,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 3.5 * 60 * 60_000,
  },

  // ── Village 1 ──────────────────────────────────────────────────────────
  {
    id: "mock-17",
    title: "V1 Ping Pong",
    emoji: "🏓",
    category: "Gaming",
    zone: "Village 1 Rec Room",
    joined: 2,
    maxPeople: 4,
    startingIn: "Tonight 8:30 PM",
    duration: "1 hr",
    distance: "-",
    description: "Round robin ping pong. Loser buys Tim's.",
    lat: 43.4700,
    lng: -80.5492,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 6.5 * 60 * 60_000,
  },

  // ── Uptown / off-campus ────────────────────────────────────────────────
  {
    id: "mock-18",
    title: "Boba Run",
    emoji: "🧋",
    category: "Food",
    zone: "Chatime Waterloo",
    joined: 2,
    maxPeople: 4,
    startingIn: "Today 3:00 PM",
    duration: "45 min",
    distance: "-",
    description: "Post-class boba. Meeting outside Chatime.",
    lat: 43.4728,
    lng: -80.5280,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 1 * 60 * 60_000,
  },
  {
    id: "mock-19",
    title: "Uptown Pizza Night",
    emoji: "🍕",
    category: "Food",
    zone: "Pizza Nova Uptown",
    joined: 4,
    maxPeople: 6,
    startingIn: "Tonight 7:30 PM",
    duration: "1 hr",
    distance: "-",
    description: "Group order - splitting a couple large pizzas.",
    lat: 43.4660,
    lng: -80.5222,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 5.5 * 60 * 60_000,
  },
  {
    id: "mock-20",
    title: "Waterloo Park Run",
    emoji: "🏃",
    category: "Sports",
    zone: "Waterloo Park Entrance",
    joined: 4,
    maxPeople: 10,
    startingIn: "Tomorrow 7:00 AM",
    duration: "45 min",
    distance: "-",
    description: "Easy 5K loop around the park. All paces welcome.",
    lat: 43.4677,
    lng: -80.5218,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 19 * 60 * 60_000,
  },
  {
    id: "mock-21",
    title: "Uptown Coffee Meetup",
    emoji: "☕",
    category: "Social",
    zone: "Uptown Waterloo",
    joined: 3,
    maxPeople: 6,
    startingIn: "Today 2:00 PM",
    duration: "1 hr",
    distance: "~15 min walk",
    description: "Coffee and chat uptown - outside main campus.",
    lat: 43.4645,
    lng: -80.5180,
    creator: "?",
    creatorAvatar: "?",
    startTimeMs: Date.now() + 30 * 60_000,
  },
];

export const MOCK_MAP_EVENTS: MapBubble[] = RAW_MOCK_EVENTS.map((e) => ({
  ...e,
  onCampus: isOnCampus(e.lat, e.lng),
}));

export const MOCK_EVENT_IDS = new Set(MOCK_MAP_EVENTS.map((e) => e.id));

export function getMockEventById(id: string): MapBubble | undefined {
  return MOCK_MAP_EVENTS.find((e) => e.id === id);
}
