-- BASELINE SCHEMA CAPTURE
-- ----------------------------------------------------------------------------
-- This migration documents the schema as it already exists live in the
-- "Wanderers Project" Supabase instance (project ref dlrbgiczzhwdegqdabwq),
-- pulled directly from the database via the Supabase MCP server. It predates
-- every other migration in this folder — dated 2026-08-20 to sort first —
-- and exists purely so the schema lives in git instead of only in the
-- dashboard. Every statement is written with IF NOT EXISTS / OR REPLACE so
-- it is safe to run against the live project (it will no-op there) and can
-- also bootstrap a brand-new empty Supabase project from scratch.
--
-- Do NOT edit this file to reflect future schema changes - write a new
-- dated migration instead, same as 20260826_bubble_stars_and_cleanup.sql
-- did for the bubble_stars table.
-- ----------------------------------------------------------------------------

-- 1. users --------------------------------------------------------------------
-- One row per auth.users account. id is both PK and FK to auth.users(id),
-- cascade-deleted when the auth user is deleted.

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text,
  campus_verified boolean default false,
  created_at timestamptz default now(),
  vibe text,
  personality_traits text[],
  interests text[],
  constraint users_vibe_check check (
    vibe is null or vibe = any (array['late_night_grinder','coffee_regular','sports','study_buddy','explorer'])
  )
);

alter table public.users enable row level security;

drop policy if exists "users_select_authenticated" on public.users;
create policy "users_select_authenticated" on public.users
  for select to authenticated using (true);

drop policy if exists "users_select_own" on public.users;
create policy "users_select_own" on public.users
  for select to authenticated using (auth.uid() = id);

drop policy if exists "users_insert_own" on public.users;
create policy "users_insert_own" on public.users
  for insert to authenticated with check (auth.uid() = id);

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own" on public.users
  for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

-- 2. bubbles --------------------------------------------------------------------
-- A bubble is a campus meetup/event. creator_id cascade-deletes with its
-- creator's account.

create table if not exists public.bubbles (
  id uuid primary key default gen_random_uuid(),
  creator_id uuid references public.users(id) on delete cascade,
  activity text not null,
  zone text not null,
  exact_location text,
  time_window text not null,
  expires_at timestamptz not null,
  status text default 'open' check (status = any (array['open','active','expired'])),
  created_at timestamptz default now(),
  max_members integer,
  start_time timestamptz,
  duration_minutes integer,
  emoji text,
  description text,
  lat double precision,
  lng double precision
);

alter table public.bubbles enable row level security;

drop policy if exists "bubbles_select_creator" on public.bubbles;
create policy "bubbles_select_creator" on public.bubbles
  for select to authenticated using (auth.uid() = creator_id);

drop policy if exists "bubbles_select_open_active" on public.bubbles;
create policy "bubbles_select_open_active" on public.bubbles
  for select to authenticated using (status = any (array['open','active']));

drop policy if exists "bubbles_insert_authenticated" on public.bubbles;
create policy "bubbles_insert_authenticated" on public.bubbles
  for insert to authenticated with check (auth.uid() = creator_id);

drop policy if exists "bubbles_update_creator" on public.bubbles;
create policy "bubbles_update_creator" on public.bubbles
  for update to authenticated using (auth.uid() = creator_id) with check (auth.uid() = creator_id);

drop policy if exists "bubbles_delete_creator" on public.bubbles;
create policy "bubbles_delete_creator" on public.bubbles
  for delete to authenticated using (auth.uid() = creator_id);

-- 3. bubble_members ---------------------------------------------------------
-- Join table: who's in which bubble's group chat. Composite PK, both FKs
-- cascade so leaving/deleting either side cleans this up automatically.

create table if not exists public.bubble_members (
  bubble_id uuid not null references public.bubbles(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  joined_at timestamptz default now(),
  primary key (bubble_id, user_id)
);

alter table public.bubble_members enable row level security;

drop policy if exists "bubble_members_select_authenticated" on public.bubble_members;
create policy "bubble_members_select_authenticated" on public.bubble_members
  for select to authenticated using (true);

drop policy if exists "bubble_members_insert_self" on public.bubble_members;
create policy "bubble_members_insert_self" on public.bubble_members
  for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "bubble_members_delete_self" on public.bubble_members;
create policy "bubble_members_delete_self" on public.bubble_members
  for delete to authenticated using (auth.uid() = user_id);

-- 4. messages -----------------------------------------------------------------
-- Bubble group-chat messages. bubble_id cascades (deleting a bubble deletes
-- its messages); user_id does NOT cascade (on_delete: no action) - a
-- deleted user's messages stay in the chat history with a dangling user_id.

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  bubble_id uuid references public.bubbles(id) on delete cascade,
  user_id uuid references public.users(id),
  content text not null,
  created_at timestamptz default now()
);

alter table public.messages enable row level security;

drop policy if exists "messages_select_members" on public.messages;
create policy "messages_select_members" on public.messages
  for select to authenticated using (
    exists (select 1 from public.bubble_members bm where bm.bubble_id = messages.bubble_id and bm.user_id = auth.uid())
  );

drop policy if exists "messages_insert_members" on public.messages;
create policy "messages_insert_members" on public.messages
  for insert to authenticated with check (
    auth.uid() = user_id
    and exists (select 1 from public.bubble_members bm where bm.bubble_id = messages.bubble_id and bm.user_id = auth.uid())
  );

-- 5. connections --------------------------------------------------------------
-- Friend-request style connections between two users. Composite PK on the
-- (requester, receiver) pair; both FKs cascade.

create table if not exists public.connections (
  requester_id uuid not null references public.users(id) on delete cascade,
  receiver_id uuid not null references public.users(id) on delete cascade,
  status text default 'pending',
  created_at timestamptz default now(),
  id uuid,
  primary key (requester_id, receiver_id)
);

alter table public.connections enable row level security;

drop policy if exists "connections_select_participants" on public.connections;
create policy "connections_select_participants" on public.connections
  for select to authenticated using (auth.uid() = requester_id or auth.uid() = receiver_id);

drop policy if exists "connections_insert_as_requester" on public.connections;
create policy "connections_insert_as_requester" on public.connections
  for insert to authenticated with check (auth.uid() = requester_id);

drop policy if exists "connections_update_receiver" on public.connections;
create policy "connections_update_receiver" on public.connections
  for update to authenticated using (auth.uid() = receiver_id) with check (auth.uid() = receiver_id);

-- 6. direct_messages ------------------------------------------------------------
-- 1:1 DMs between two users. Neither FK cascades (on_delete: no action) -
-- deleting a user does NOT clean these up; a dangling sender/receiver_id
-- would be left behind. Worth revisiting if user deletion is ever exposed.

create table if not exists public.direct_messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.users(id),
  receiver_id uuid not null references public.users(id),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.direct_messages enable row level security;

drop policy if exists "dm_select_participants" on public.direct_messages;
create policy "dm_select_participants" on public.direct_messages
  for select to authenticated using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "dm_insert_as_sender" on public.direct_messages;
create policy "dm_insert_as_sender" on public.direct_messages
  for insert to authenticated with check (auth.uid() = sender_id);

-- 7. meetup_photos --------------------------------------------------------------
-- "Wander Moments" feed photos tied to a bubble. Neither FK cascades.

create table if not exists public.meetup_photos (
  id uuid primary key default gen_random_uuid(),
  bubble_id uuid references public.bubbles(id),
  user_id uuid references public.users(id),
  cloudinary_url text,
  created_at timestamptz default now(),
  caption text
);

alter table public.meetup_photos enable row level security;

drop policy if exists "meetup_photos_select_authenticated" on public.meetup_photos;
create policy "meetup_photos_select_authenticated" on public.meetup_photos
  for select to authenticated using (true);

drop policy if exists "meetup_photos_insert_self" on public.meetup_photos;
create policy "meetup_photos_insert_self" on public.meetup_photos
  for insert to authenticated with check (auth.uid() = user_id);

-- 8. campus_events --------------------------------------------------------------
-- Official UW events, scraped/seeded separately. Read-only from the app's
-- perspective - no insert/update/delete policies exist.

create table if not exists public.campus_events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  location text not null,
  zone text,
  date_time timestamptz not null,
  organizer text,
  category text check (category = any (array['academic','social','sports','arts','career'])),
  source_url text,
  created_at timestamptz not null default now()
);

alter table public.campus_events enable row level security;

drop policy if exists "campus_events_select_authenticated" on public.campus_events;
create policy "campus_events_select_authenticated" on public.campus_events
  for select to authenticated using (true);

-- ----------------------------------------------------------------------------
-- NOTE: public.bubble_stars is intentionally NOT included here - it's
-- created by 20260826_bubble_stars_and_cleanup.sql, which also defines the
-- cleanup_expired_bubbles() function and its pg_cron schedule.
--
-- NOTE on RLS in this app: every API route in src/app/api/ uses the
-- service-role admin client (src/lib/supabaseAdmin.ts), which BYPASSES RLS
-- entirely. The policies above are captured faithfully from what's live,
-- but they are not the actual authorization boundary for anything routed
-- through the Next.js API - that's enforced by hand in each route handler
-- (e.g. ensureBubbleMembership). RLS only matters here for any query made
-- directly from the browser with the anon key, which today is limited to
-- Supabase Realtime subscriptions (see src/app/api/README.md).
-- ----------------------------------------------------------------------------
